services:
  catsoop:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7667:7667"
      - "7668:7668"
    volumes:
      - catsoop_data:/app/data
      - .:/.local/share/catsoop/courses/number_sense/
      - ./config.py:/root/.config/catsoop/config.py
    restart: unless-stopped
volumes:
  catsoop_data: 